// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "index": {
      name: "index",
      description: "",
      type: "registry:style",
      registryDependencies: ["utils"],
      files: [],
      source: "",
      chunks: []
    },
    "style": {
      name: "style",
      description: "",
      type: "registry:style",
      registryDependencies: ["utils"],
      files: [],
      source: "",
      chunks: []
    },
    "heading": {
      name: "heading",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/heading.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/heading.tsx")),
      source: "",
      chunks: []
    },
    "message": {
      name: "message",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/message.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/message.tsx")),
      source: "",
      chunks: []
    },
    "utils": {
      name: "utils",
      description: "",
      type: "registry:lib",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/lib/utils.ts",
        type: "registry:lib",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/lib/utils.ts")),
      source: "",
      chunks: []
    },
    "compose-refs": {
      name: "compose-refs",
      description: "",
      type: "registry:lib",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/lib/compose-refs.ts",
        type: "registry:lib",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/lib/compose-refs.ts")),
      source: "",
      chunks: []
    },
    "use-as-ref": {
      name: "use-as-ref",
      description: "",
      type: "registry:hook",
      registryDependencies: ["@aloeui/use-isomorphic-layout-effect"],
      files: [{
        path: "registry/default/hooks/use-as-ref.ts",
        type: "registry:hook",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/hooks/use-as-ref.ts")),
      source: "",
      chunks: []
    },
    "use-isomorphic-layout-effect": {
      name: "use-isomorphic-layout-effect",
      description: "",
      type: "registry:hook",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/hooks/use-isomorphic-layout-effect.ts",
        type: "registry:hook",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/hooks/use-isomorphic-layout-effect.ts")),
      source: "",
      chunks: []
    },
    "use-lazy-ref": {
      name: "use-lazy-ref",
      description: "",
      type: "registry:hook",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/hooks/use-lazy-ref.ts",
        type: "registry:hook",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/hooks/use-lazy-ref.ts")),
      source: "",
      chunks: []
    },
    "use-mobile": {
      name: "use-mobile",
      description: "",
      type: "registry:hook",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/hooks/use-mobile.ts",
        type: "registry:hook",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/hooks/use-mobile.ts")),
      source: "",
      chunks: []
    },
    "heading-demo": {
      name: "heading-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["heading"],
      files: [{
        path: "registry/default/examples/heading-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/heading-demo.tsx")),
      source: "",
      chunks: []
    },
    "message-demo": {
      name: "message-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["message"],
      files: [{
        path: "registry/default/examples/message-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/message-demo.tsx")),
      source: "",
      chunks: []
    },
    "client-only": {
      name: "client-only",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/components/client-only.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/components/client-only.tsx")),
      source: "",
      chunks: []
    },
    "direction-provider": {
      name: "direction-provider",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/components/direction-provider.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/components/direction-provider.tsx")),
      source: "",
      chunks: []
    },
    "hitbox": {
      name: "hitbox",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/components/hitbox.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/components/hitbox.tsx")),
      source: "",
      chunks: []
    },
    "portal": {
      name: "portal",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/components/portal.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/components/portal.tsx")),
      source: "",
      chunks: []
    },
    "pending": {
      name: "pending",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/components/pending.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/components/pending.tsx")),
      source: "",
      chunks: []
    },
    "presence": {
      name: "presence",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/components/presence.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/components/presence.tsx")),
      source: "",
      chunks: []
    },
    "visually-hidden": {
      name: "visually-hidden",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/components/visually-hidden.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/components/visually-hidden.tsx")),
      source: "",
      chunks: []
    },
    "visually-hidden-input": {
      name: "visually-hidden-input",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/components/visually-hidden-input.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/components/visually-hidden-input.tsx")),
      source: "",
      chunks: []
    },
  },
}
